# Generated by Django 3.2.6 on 2021-12-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cofradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(max_length=100)),
                ('foundation', models.CharField(max_length=4)),
                ('association', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dance', models.CharField(max_length=50)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('image', models.ImageField(upload_to='images')),
                ('performance', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('costume', models.CharField(max_length=255)),
                ('guild', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('apertureValue', models.CharField(default='', max_length=255)),
                ('exposureTime', models.CharField(default='', max_length=255)),
                ('focalLength', models.CharField(default='', max_length=255)),
                ('iso', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
