# Generated by Django 3.2.6 on 2021-08-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='costume',
            field=models.CharField(default='vestimenta', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='guild',
            field=models.CharField(default='sociedad de baile', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='performance',
            field=models.CharField(default='baile', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(default='año', max_length=4),
        ),
    ]
