# Generated by Django 3.2.6 on 2021-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0005_alter_post_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='costume',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='performance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
