# Generated by Django 3.2.6 on 2021-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0006_auto_20210823_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='guild',
            field=models.CharField(choices=[('sociedad religiosa chilenitos de santa teresita', '\u200b\u200bSOCIEDAD RELIGIOSA CHILENITOS DE SANTA TERESITA'), ('sociedad católica indios tobas del norte virgen de la tirana', 'SOCIEDAD CATÓLICA INDIOS TOBAS DEL NORTE VIRGEN DE LA TIRANA'), ('sociedad religiosa gitanos del carmen trinidad ponce', 'SOCIEDAD RELIGIOSA GITANOS DEL CARMEN TRINIDAD PONCE'), ('baile religioso auténtica diablada', 'BAILE RELIGIOSO AUTÉNTICA DIABLADA'), ('baile religioso aymara', 'BAILE RELIGIOSO AYMARA'), ('sociedad religiosa siervos de jesús y maría', 'SOCIEDAD RELIGIOSA SIERVOS DE JESÚS Y MARÍA')], default='Sociedad Religiosa Chilenitos de Santa Teresita', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
