# Generated by Django 3.2.6 on 2021-12-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0007_auto_20211212_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='character',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
